

title: Jack J. Lee | Science Writer
email: jackjleescience@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Jack J. Lee is a science journalist training in the Science Communcation Program at UC Santa Cruz
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jackjlee
github_username:  jackjlee

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

author:
  name     : "Jack J. Lee"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Science-writer-in-training at UC Santa Cruz"
  links:
      - label: "Email"
        icon: "fas fa-envelope"
        url: "mailto:jackjleescience@gmail.com"
      - label: "Twitter"
        icon: "fab fa-twitter"
        url: "https://twitter.com/jackjlee"
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/jackjlee"

footer:
  links:
      - label: "Email"
        icon: "fas fa-envelope"
        url: "mailto:jackjleescience@gmail.com"
      - label: "Twitter"
        icon: "fab fa-twitter"
        url: "https://twitter.com/jackjlee"
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/jackjlee"
